### ISSUE TITLE
Güvenlik

### ISSUE THREAD

**Issue by ccali14** [oguzhantasci/ingilizcekelimelik.com#27]
Mantıksal güvenlik açıkları mevcut.

**Comment by oguzhantasci** [comment]
detayları paylaşırmısın @ccali14

**Comment by ccali14** [comment]
Başkalarının box'larını silebiliyor, içeriğini görüntüleyebiliyor ve düzenleyebiliyorum, bu durumda kullanıcı girişinin bir anlamı yok.

**Comment by oguzhantasci** [comment]
Detaylı işlemlerin linklerini alabilirsem incelemek isterim.  @ccali14
